Refactor retry script

diff --git a/bin/retry b/bin/retry
--- a/bin/retry
+++ b/bin/retry
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
 # Stolen from https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_retry.bash
 
@@ -8,9 +8,10 @@ retry() {
   local ANSI_RESET="\033[0m"
   local result=0
   local count=1
-  while [ $count -le 3 ]; do
+  local max=3
+  while [ $count -le $max ]; do
     [ $result -ne 0 ] && {
-      echo -e "\n${ANSI_RED}The command \"$@\" failed. Retrying, $count of 3.${ANSI_RESET}\n" >&2
+      echo -e "\n${ANSI_RED}The command \"$@\" failed. Retrying, $count of $max.${ANSI_RESET}\n" >&2
     }
     "$@"
     result=$?
@@ -19,8 +20,8 @@ retry() {
     sleep 5
   done
 
-  [ $count -gt 3 ] && {
-    echo -e "\n${ANSI_RED}The command \"$@\" failed 3 times.${ANSI_RESET}\n" >&2
+  [ $count -gt $max ] && {
+    echo -e "\n${ANSI_RED}The command \"$@\" failed $max times.${ANSI_RESET}\n" >&2
   }
 
   return $result
